name: X Auto Post GitHub Trending

on:
  schedule:
    # 毎日朝6:30（UTC 21:30, JST 06:30）
    - cron: '30 21 * * *'
    # 毎日夜18:00（UTC 09:00, JST 18:00）  
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode (dry run)'
        required: false
        default: 'false'
        type: choice
        options:
        - 'false'
        - 'true'

permissions:
  contents: read
  issues: write

jobs:
  post-trending:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run trending post automation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          X_OAUTH2_ACCESS_TOKEN: ${{ secrets.X_OAUTH2_ACCESS_TOKEN }}
          REQUIRE_OAUTH2: 'true'
          TEST_MODE: ${{ github.event.inputs.test_mode }}
        run: |
          if [ "$TEST_MODE" = "true" ]; then
            echo "Running in test mode..."
            node src/test.js
          else
            echo "Running in production mode..."
            node src/auto-post.js
          fi